name: Build on push

on:
  push:
    branches:
      - master
      - next

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read

jobs:
  build:
    uses: ./.github/workflows/build-yocto.yml
  test:
    uses: ./.github/workflows/test.yml
    needs: [build]
    secrets: inherit
    with:
      build_id: ${{ github.run_id }}
